In [12]:
import pandas as pd
import numpy as np
from sklearn.neighbors import KNeighborsClassifier

In [20]:
train_data = pd.read_csv('train.csv')
test_data = pd.read_csv('test.csv')

In [13]:
y_train = train_data['label']
x_train = np.array(train_data.iloc[:, 1:])

In [17]:
x_train.shape

(42000, 784)

In [18]:
y_train.shape

(42000,)

In [22]:
test_data

,pixel0,pixel1,pixel2,pixel3,pixel4,pixel5,pixel6,pixel7,pixel8,pixel9,...,pixel774,pixel775,pixel776,pixel777,pixel778,pixel779,pixel780,pixel781,pixel782,pixel783
0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
27995,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
27996,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
27997,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
27998,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
27999,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [23]:
x_test = np.array(test_data.iloc[:, :])

In [24]:
model = KNeighborsClassifier(n_neighbors=3)
model.fit(x_train, y_train)
y_pred = model.predict(x_test)

In [25]:
y_pred.shape

(28000,)

In [31]:
import csv
column_names = ['ImageId', 'Label']
file_name = 'output.csv'
final_arr = []
for i in range(len(y_pred)):
  final_arr.append([i+1, y_pred[i]])
with open(file_name, 'w') as csvfile: 
    csvwriter = csv.writer(csvfile) 
    csvwriter.writerow(column_names) 
    csvwriter.writerows(final_arr)